"""Small default teaching canon for Blink's knowledge scaffold."""

from __future__ import annotations

from blink.brain.knowledge.registry import KnowledgeReserveRegistry
from blink.brain.knowledge.schema import (
    ExplanationExemplar,
    KnowledgeReserveEntry,
    TeachingSequence,
)

_DEFAULT_SOURCE = "blink-default-teaching-canon"
_DEFAULT_PROVENANCE = {
    "curator": "blink",
    "kind": "internal-pedagogy",
    "version": "2026-04",
}


DEFAULT_TEACHING_CANON = KnowledgeReserveRegistry.from_entries(
    entries=(
        KnowledgeReserveEntry(
            entry_id="reserve:source_grounding_policy",
            title="Source grounding and uncertainty",
            summary=(
                "For source-sensitive teaching, say what is known, name uncertainty, "
                "and avoid fabricated citations."
            ),
            body=(
                "Use only available sources or repo-visible context. When support is missing, "
                "state uncertainty early and do not invent paper, book, article, or benchmark "
                "citations."
            ),
            tags=("source", "grounding", "uncertainty", "citation", "teaching"),
            languages=("en", "zh"),
            task_modes=("reply",),
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.74,
        ),
    ),
    exemplars=(
        ExplanationExemplar(
            exemplar_id="exemplar:chinese_technical_explanation_bridge",
            title="Chinese technical explanation bridge",
            query_terms=(
                "解释",
                "技术",
                "递归",
                "调试",
                "报错",
                "修复",
                "排查",
                "复现",
                "练习",
                "代码",
                "概念",
                "例子",
                "原理",
                "误解",
                "technical",
                "debug",
                "source",
                "practice",
            ),
            teaching_modes=("walkthrough", "clarify"),
            task_modes=("reply",),
            language="zh",
            prompt_pattern=("用中文解释核心思路，保留必要英文术语，先给直觉，再给小例子。"),
            explanation=("先用自然中文说明问题，再用一个很小的 technical example 连接术语和操作。"),
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.9,
        ),
        ExplanationExemplar(
            exemplar_id="exemplar:direct_answer_then_optional_detail",
            title="Direct answer then optional detail",
            query_terms=(
                "concise",
                "brief",
                "direct",
                "quick",
                "explain",
                "answer",
                "summary",
                "short",
            ),
            teaching_modes=("clarify",),
            task_modes=("reply",),
            language="en",
            prompt_pattern="Answer first in one sentence, then add one optional detail if useful.",
            explanation="Lead with the result, then give a compact reason or next step.",
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.78,
        ),
        ExplanationExemplar(
            exemplar_id="exemplar:walkthrough_small_example",
            title="Walkthrough with a small example",
            query_terms=(
                "explain",
                "concept",
                "example",
                "walkthrough",
                "intuition",
                "recursion",
                "debug",
                "technical",
                "small",
            ),
            teaching_modes=("walkthrough", "clarify"),
            task_modes=("reply",),
            language="en",
            prompt_pattern="State the intuition, give a tiny example, then generalize.",
            explanation="Use a small concrete case before naming the broader rule.",
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.86,
        ),
        ExplanationExemplar(
            exemplar_id="exemplar:debugging_hypothesis_one_change",
            title="Debugging hypothesis with one changed variable",
            query_terms=(
                "debug",
                "bug",
                "failure",
                "failing",
                "error",
                "traceback",
                "minimal",
                "repro",
                "hypothesis",
                "one-change",
                "one",
                "change",
            ),
            teaching_modes=("walkthrough", "clarify"),
            task_modes=("reply",),
            language="en",
            prompt_pattern="Separate observed symptom, expected behavior, and one testable change.",
            explanation="Name one hypothesis, change one variable, and use the result to choose the next step.",
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.88,
        ),
        ExplanationExemplar(
            exemplar_id="exemplar:misconception_repair_without_shame",
            title="Misconception repair without shame",
            query_terms=(
                "misconception",
                "confused",
                "wrong",
                "actually",
                "correction",
                "correct",
                "misunderstand",
                "repair",
                "explain",
            ),
            teaching_modes=("clarify", "walkthrough"),
            task_modes=("reply",),
            language="en",
            prompt_pattern="State the correction directly, then show the small distinction that caused the mix-up.",
            explanation="Correct the idea, not the person; avoid shaming language and give one tiny contrast.",
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.84,
        ),
        ExplanationExemplar(
            exemplar_id="exemplar:source_grounded_answer_with_limits",
            title="Source-grounded answer with limits",
            query_terms=(
                "source",
                "sources",
                "citation",
                "cite",
                "grounded",
                "evidence",
                "uncertain",
                "unknown",
                "documentation",
                "reference",
                "prove",
            ),
            teaching_modes=("clarify", "walkthrough"),
            task_modes=("reply",),
            language="en",
            prompt_pattern="Answer from available context, name the limit, and avoid invented citations.",
            explanation="Say what the visible source supports, what remains uncertain, and what would verify it.",
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.86,
        ),
    ),
    teaching_sequences=(
        TeachingSequence(
            sequence_id="sequence:debugging_minimal_repro",
            title="Debugging minimal reproduction sequence",
            query_terms=(
                "debug",
                "bug",
                "error",
                "traceback",
                "failing",
                "hypothesis",
                "one-change",
                "minimal",
                "repro",
                "reproduction",
                "调试",
                "报错",
                "复现",
            ),
            teaching_modes=("walkthrough", "clarify"),
            task_modes=("reply",),
            language="en",
            steps=(
                "Name the observed symptom.",
                "State the expected behavior.",
                "Reduce to the smallest input or call path.",
                "Change one variable and test the fix.",
            ),
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.82,
        ),
        TeachingSequence(
            sequence_id="sequence:practice_prompt_with_answer_key",
            title="Practice prompt with answer key",
            query_terms=(
                "practice",
                "exercise",
                "prompt",
                "problem",
                "quiz",
                "answer",
                "key",
                "recursion",
                "examples",
                "练习",
                "答案",
            ),
            teaching_modes=("walkthrough", "clarify"),
            task_modes=("reply",),
            language="en",
            steps=(
                "Give one small practice prompt.",
                "State the expected answer or key idea.",
                "Add one hint only if it reduces ambiguity.",
                "Keep the scope narrow enough to answer immediately.",
            ),
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.8,
        ),
        TeachingSequence(
            sequence_id="sequence:learning_check_without_overquestioning",
            title="Learning check without overquestioning",
            query_terms=(
                "teach",
                "learn",
                "understand",
                "question",
                "check",
                "examples",
                "explain",
            ),
            teaching_modes=("walkthrough", "clarify"),
            task_modes=("reply",),
            language="en",
            steps=(
                "Explain the core move.",
                "Use one targeted example.",
                "Ask at most one diagnostic question if it would change the next step.",
            ),
            source=_DEFAULT_SOURCE,
            provenance=_DEFAULT_PROVENANCE,
            priority=0.7,
        ),
    ),
)


def build_default_teaching_canon() -> KnowledgeReserveRegistry:
    """Return Blink's default teaching canon registry."""
    return DEFAULT_TEACHING_CANON


__all__ = ["DEFAULT_TEACHING_CANON", "build_default_teaching_canon"]
