"""Blink brain compatibility surface with lazy exports."""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "BRAIN_CONTEXT_HEADER",
    "BrainActionEventRecord",
    "BrainActiveContextAnchorCandidate",
    "BrainActiveContextCompiler",
    "BrainActiveContextExpansionRecord",
    "BrainActiveContextPacket",
    "BrainActiveContextPacketItemRecord",
    "BrainActiveContextTrace",
    "BrainAgendaProjection",
    "BrainAutonomyDecisionKind",
    "BrainAutonomyLedgerEntry",
    "BrainAutonomyLedgerProjection",
    "BrainBlockedReason",
    "BrainBlockedReasonKind",
    "BrainCandidateGoal",
    "BrainCandidateGoalSource",
    "BrainCommitmentProjection",
    "BrainCommitmentRecord",
    "BrainCommitmentScopeType",
    "BrainCommitmentStatus",
    "BrainCommitmentWakeRouteKind",
    "BrainCommitmentWakeRoutingDecision",
    "BrainCommitmentWakeTrigger",
    "BrainConsolidationResult",
    "BrainContextBudgetProfile",
    "BrainContextCompiler",
    "BrainContextCompilerProcessor",
    "BrainContextTemporalMode",
    "BrainExpressionVoicePolicyProcessor",
    "BrainContextSelectionTrace",
    "BrainContextSelector",
    "BrainContextSurfaceBuilder",
    "BrainContextSurfaceSnapshot",
    "BrainContextTask",
    "BrainContinuityAuditExporter",
    "BrainContinuityAuditReport",
    "BrainContinuityEvalCase",
    "BrainContinuityEvalHarness",
    "BrainContinuityEvalResult",
    "BrainContinuityExpectedState",
    "BrainCoreReplayHarness",
    "BrainCoreReplayResult",
    "BrainCoreReplayScenario",
    "BrainCoreStore",
    "BrainEngagementStateProjection",
    "BrainEpisodeRecord",
    "BrainEventRecord",
    "BrainEventRecorderProcessor",
    "BrainEventType",
    "BrainExecutive",
    "BrainExecutiveCycleResult",
    "BrainFactCandidate",
    "BrainFactRecord",
    "BrainGoal",
    "BrainGoalFamily",
    "BrainGoalStatus",
    "BrainGoalStep",
    "BrainHeartbeatProjection",
    "BrainMemoryConsolidator",
    "BrainMemoryEmbeddingProvider",
    "BrainMemoryQuery",
    "BrainMemoryRetriever",
    "BrainMemorySearchResult",
    "BrainPresenceSnapshot",
    "BrainReevaluationTrigger",
    "BrainReevaluationConditionKind",
    "BrainRelationshipStateProjection",
    "BrainReplayHarness",
    "BrainReplayResult",
    "BrainReplayScenario",
    "BrainRuntime",
    "BrainRuntimeCommitmentControlResult",
    "BrainRuntimePacketInspection",
    "BrainRuntimePendingWakeInspection",
    "BrainRuntimeShell",
    "BrainRuntimeShellSnapshot",
    "BrainSceneStateProjection",
    "BrainSessionIds",
    "BrainSelectedContext",
    "BrainSpeechChunk",
    "SpeechPerformanceChunk",
    "SpeechChunkBudgetV3",
    "BrainStore",
    "BrainTaskCandidate",
    "BrainInitiativeClass",
    "BrainWakeCondition",
    "BrainWakeConditionKind",
    "BrainWorkingContextProjection",
    "BrainWorkingMemorySnapshot",
    "CapabilityDefinition",
    "CapabilityExecutionContext",
    "CapabilityExecutionResult",
    "CapabilityRegistry",
    "EmbodiedActionDefinition",
    "EmbodiedActionEngine",
    "EmbodiedActionLibrary",
    "EmbodiedCapabilityDispatcher",
    "EmbodiedCommandClassifierResult",
    "EmbodiedCommandInterpretation",
    "EmbodiedCommandInterpreter",
    "EmbodiedCommandProcessor",
    "HotPathMemoryExtractor",
    "BrainConversationStep",
    "BrainCompiledContextPacket",
    "TurnRecorderProcessor",
    "base_brain_system_prompt",
    "build_embodied_capability_registry",
    "build_user_profile_summary",
    "build_working_memory_snapshot",
    "capability_id_for_action",
    "embodied_action_tool_prompt",
    "extract_memory_candidates",
    "extract_task_candidates",
    "load_default_agent_blocks",
    "memory_tool_prompt",
    "normalize_presence_snapshot",
    "register_embodied_action_tools",
    "register_memory_tools",
    "render_agenda_summary",
    "render_capability_manifest",
    "render_heartbeat_summary",
    "render_presence_summary",
    "render_recent_memory_summary",
    "render_relationship_continuity_summary",
    "render_relationship_state_summary",
    "render_scene_summary",
    "render_user_profile_summary",
    "render_working_context_summary",
    "resolve_brain_session_ids",
]

_EXPORTS = {
    "BRAIN_CONTEXT_HEADER": ("blink.brain.identity", "BRAIN_CONTEXT_HEADER"),
    "BrainActionEventRecord": ("blink.brain.store", "BrainActionEventRecord"),
    "BrainAgendaProjection": ("blink.brain.projections", "BrainAgendaProjection"),
    "BrainAutonomyDecisionKind": ("blink.brain.autonomy", "BrainAutonomyDecisionKind"),
    "BrainAutonomyLedgerEntry": ("blink.brain.autonomy", "BrainAutonomyLedgerEntry"),
    "BrainAutonomyLedgerProjection": ("blink.brain.autonomy", "BrainAutonomyLedgerProjection"),
    "BrainBlockedReason": ("blink.brain.projections", "BrainBlockedReason"),
    "BrainBlockedReasonKind": ("blink.brain.projections", "BrainBlockedReasonKind"),
    "BrainCandidateGoal": ("blink.brain.autonomy", "BrainCandidateGoal"),
    "BrainCandidateGoalSource": ("blink.brain.autonomy", "BrainCandidateGoalSource"),
    "BrainReevaluationTrigger": ("blink.brain.autonomy", "BrainReevaluationTrigger"),
    "BrainReevaluationConditionKind": ("blink.brain.autonomy", "BrainReevaluationConditionKind"),
    "BrainCommitmentProjection": ("blink.brain.projections", "BrainCommitmentProjection"),
    "BrainCommitmentRecord": ("blink.brain.projections", "BrainCommitmentRecord"),
    "BrainCommitmentScopeType": ("blink.brain.projections", "BrainCommitmentScopeType"),
    "BrainCommitmentStatus": ("blink.brain.projections", "BrainCommitmentStatus"),
    "BrainCommitmentWakeRouteKind": (
        "blink.brain.projections",
        "BrainCommitmentWakeRouteKind",
    ),
    "BrainCommitmentWakeRoutingDecision": (
        "blink.brain.projections",
        "BrainCommitmentWakeRoutingDecision",
    ),
    "BrainCommitmentWakeTrigger": ("blink.brain.projections", "BrainCommitmentWakeTrigger"),
    "BrainConsolidationResult": ("blink.brain.memory", "BrainConsolidationResult"),
    "BrainActiveContextAnchorCandidate": (
        "blink.brain.context",
        "BrainActiveContextAnchorCandidate",
    ),
    "BrainActiveContextCompiler": ("blink.brain.context", "BrainActiveContextCompiler"),
    "BrainActiveContextExpansionRecord": (
        "blink.brain.context",
        "BrainActiveContextExpansionRecord",
    ),
    "BrainActiveContextPacket": ("blink.brain.context", "BrainActiveContextPacket"),
    "BrainActiveContextPacketItemRecord": (
        "blink.brain.context",
        "BrainActiveContextPacketItemRecord",
    ),
    "BrainActiveContextTrace": ("blink.brain.context", "BrainActiveContextTrace"),
    "BrainContextBudgetProfile": ("blink.brain.context", "BrainContextBudgetProfile"),
    "BrainContextCompiler": ("blink.brain.context", "BrainContextCompiler"),
    "BrainCompiledContextPacket": ("blink.brain.context", "BrainCompiledContextPacket"),
    "BrainContextCompilerProcessor": ("blink.brain.processors", "BrainContextCompilerProcessor"),
    "BrainContextTemporalMode": ("blink.brain.context", "BrainContextTemporalMode"),
    "BrainExpressionVoicePolicyProcessor": (
        "blink.brain.processors",
        "BrainExpressionVoicePolicyProcessor",
    ),
    "BrainContextSelectionTrace": ("blink.brain.context", "BrainContextSelectionTrace"),
    "BrainContextSelector": ("blink.brain.context", "BrainContextSelector"),
    "BrainContextSurfaceBuilder": ("blink.brain.context_surfaces", "BrainContextSurfaceBuilder"),
    "BrainContextSurfaceSnapshot": ("blink.brain.context_surfaces", "BrainContextSurfaceSnapshot"),
    "BrainContextTask": ("blink.brain.context", "BrainContextTask"),
    "BrainContinuityAuditExporter": ("blink.brain.evals", "BrainContinuityAuditExporter"),
    "BrainContinuityAuditReport": ("blink.brain.evals", "BrainContinuityAuditReport"),
    "BrainContinuityEvalCase": ("blink.brain.evals", "BrainContinuityEvalCase"),
    "BrainContinuityEvalHarness": ("blink.brain.evals", "BrainContinuityEvalHarness"),
    "BrainContinuityEvalResult": ("blink.brain.evals", "BrainContinuityEvalResult"),
    "BrainContinuityExpectedState": ("blink.brain.evals", "BrainContinuityExpectedState"),
    "BrainCoreReplayHarness": ("blink.brain.core", "BrainCoreReplayHarness"),
    "BrainCoreReplayResult": ("blink.brain.core", "BrainCoreReplayResult"),
    "BrainCoreReplayScenario": ("blink.brain.core", "BrainCoreReplayScenario"),
    "BrainCoreStore": ("blink.brain.core", "BrainCoreStore"),
    "BrainEngagementStateProjection": ("blink.brain.projections", "BrainEngagementStateProjection"),
    "BrainEpisodeRecord": ("blink.brain.store", "BrainEpisodeRecord"),
    "BrainEventRecord": ("blink.brain.events", "BrainEventRecord"),
    "BrainEventRecorderProcessor": ("blink.brain.processors", "BrainEventRecorderProcessor"),
    "BrainEventType": ("blink.brain.events", "BrainEventType"),
    "BrainExecutive": ("blink.brain.executive", "BrainExecutive"),
    "BrainExecutiveCycleResult": ("blink.brain.executive", "BrainExecutiveCycleResult"),
    "BrainFactCandidate": ("blink.brain.memory", "BrainFactCandidate"),
    "BrainFactRecord": ("blink.brain.store", "BrainFactRecord"),
    "BrainGoal": ("blink.brain.projections", "BrainGoal"),
    "BrainGoalFamily": ("blink.brain.projections", "BrainGoalFamily"),
    "BrainGoalStatus": ("blink.brain.projections", "BrainGoalStatus"),
    "BrainGoalStep": ("blink.brain.projections", "BrainGoalStep"),
    "BrainHeartbeatProjection": ("blink.brain.projections", "BrainHeartbeatProjection"),
    "BrainMemoryConsolidator": ("blink.brain.memory", "BrainMemoryConsolidator"),
    "BrainMemoryEmbeddingProvider": ("blink.brain.memory", "BrainMemoryEmbeddingProvider"),
    "BrainMemoryQuery": ("blink.brain.memory", "BrainMemoryQuery"),
    "BrainMemoryRetriever": ("blink.brain.memory", "BrainMemoryRetriever"),
    "BrainMemorySearchResult": ("blink.brain.memory", "BrainMemorySearchResult"),
    "BrainPresenceSnapshot": ("blink.brain.presence", "BrainPresenceSnapshot"),
    "BrainRelationshipStateProjection": (
        "blink.brain.projections",
        "BrainRelationshipStateProjection",
    ),
    "BrainReplayHarness": ("blink.brain.replay", "BrainReplayHarness"),
    "BrainReplayResult": ("blink.brain.replay", "BrainReplayResult"),
    "BrainReplayScenario": ("blink.brain.replay", "BrainReplayScenario"),
    "BrainRuntime": ("blink.brain.runtime", "BrainRuntime"),
    "BrainRuntimeCommitmentControlResult": (
        "blink.brain.runtime_shell",
        "BrainRuntimeCommitmentControlResult",
    ),
    "BrainRuntimePacketInspection": ("blink.brain.runtime_shell", "BrainRuntimePacketInspection"),
    "BrainRuntimePendingWakeInspection": (
        "blink.brain.runtime_shell",
        "BrainRuntimePendingWakeInspection",
    ),
    "BrainRuntimeShell": ("blink.brain.runtime_shell", "BrainRuntimeShell"),
    "BrainRuntimeShellSnapshot": ("blink.brain.runtime_shell", "BrainRuntimeShellSnapshot"),
    "BrainSceneStateProjection": ("blink.brain.projections", "BrainSceneStateProjection"),
    "BrainSessionIds": ("blink.brain.session", "BrainSessionIds"),
    "BrainSelectedContext": ("blink.brain.context", "BrainSelectedContext"),
    "BrainSpeechChunk": ("blink.brain.speech_director", "BrainSpeechChunk"),
    "SpeechChunkBudgetV3": ("blink.brain.speech_director", "SpeechChunkBudgetV3"),
    "SpeechPerformanceChunk": ("blink.brain.speech_director", "SpeechPerformanceChunk"),
    "BrainStore": ("blink.brain.store", "BrainStore"),
    "BrainTaskCandidate": ("blink.brain.memory", "BrainTaskCandidate"),
    "BrainInitiativeClass": ("blink.brain.autonomy", "BrainInitiativeClass"),
    "BrainWakeCondition": ("blink.brain.projections", "BrainWakeCondition"),
    "BrainWakeConditionKind": ("blink.brain.projections", "BrainWakeConditionKind"),
    "BrainWorkingContextProjection": ("blink.brain.projections", "BrainWorkingContextProjection"),
    "BrainWorkingMemorySnapshot": ("blink.brain.memory", "BrainWorkingMemorySnapshot"),
    "CapabilityDefinition": ("blink.brain.capabilities", "CapabilityDefinition"),
    "CapabilityExecutionContext": ("blink.brain.capabilities", "CapabilityExecutionContext"),
    "CapabilityExecutionResult": ("blink.brain.capabilities", "CapabilityExecutionResult"),
    "CapabilityRegistry": ("blink.brain.capabilities", "CapabilityRegistry"),
    "EmbodiedActionDefinition": ("blink.brain.actions", "EmbodiedActionDefinition"),
    "EmbodiedActionEngine": ("blink.brain.actions", "EmbodiedActionEngine"),
    "EmbodiedActionLibrary": ("blink.brain.actions", "EmbodiedActionLibrary"),
    "EmbodiedCapabilityDispatcher": ("blink.brain.actions", "EmbodiedCapabilityDispatcher"),
    "EmbodiedCommandClassifierResult": ("blink.brain.actions", "EmbodiedCommandClassifierResult"),
    "EmbodiedCommandInterpretation": ("blink.brain.actions", "EmbodiedCommandInterpretation"),
    "EmbodiedCommandInterpreter": ("blink.brain.actions", "EmbodiedCommandInterpreter"),
    "EmbodiedCommandProcessor": ("blink.brain.processors", "EmbodiedCommandProcessor"),
    "HotPathMemoryExtractor": ("blink.brain.processors", "HotPathMemoryExtractor"),
    "BrainConversationStep": ("blink.brain.evals", "BrainConversationStep"),
    "TurnRecorderProcessor": ("blink.brain.processors", "TurnRecorderProcessor"),
    "base_brain_system_prompt": ("blink.brain.identity", "base_brain_system_prompt"),
    "build_embodied_capability_registry": (
        "blink.brain.actions",
        "build_embodied_capability_registry",
    ),
    "build_user_profile_summary": ("blink.brain.memory", "build_user_profile_summary"),
    "build_working_memory_snapshot": ("blink.brain.memory", "build_working_memory_snapshot"),
    "capability_id_for_action": ("blink.brain.actions", "capability_id_for_action"),
    "embodied_action_tool_prompt": ("blink.brain.actions", "embodied_action_tool_prompt"),
    "extract_memory_candidates": ("blink.brain.memory", "extract_memory_candidates"),
    "extract_task_candidates": ("blink.brain.memory", "extract_task_candidates"),
    "load_default_agent_blocks": ("blink.brain.identity", "load_default_agent_blocks"),
    "memory_tool_prompt": ("blink.brain.memory", "memory_tool_prompt"),
    "normalize_presence_snapshot": ("blink.brain.presence", "normalize_presence_snapshot"),
    "register_embodied_action_tools": ("blink.brain.actions", "register_embodied_action_tools"),
    "register_memory_tools": ("blink.brain.memory", "register_memory_tools"),
    "render_agenda_summary": ("blink.brain.projections", "render_agenda_summary"),
    "render_capability_manifest": (
        "blink.brain.capability_manifests",
        "render_capability_manifest",
    ),
    "render_heartbeat_summary": ("blink.brain.projections", "render_heartbeat_summary"),
    "render_presence_summary": ("blink.brain.presence", "render_presence_summary"),
    "render_recent_memory_summary": (
        "blink.brain.context_surfaces",
        "render_recent_memory_summary",
    ),
    "render_relationship_continuity_summary": (
        "blink.brain.context_surfaces",
        "render_relationship_continuity_summary",
    ),
    "render_relationship_state_summary": (
        "blink.brain.projections",
        "render_relationship_state_summary",
    ),
    "render_scene_summary": ("blink.brain.projections", "render_scene_summary"),
    "render_user_profile_summary": ("blink.brain.context_surfaces", "render_user_profile_summary"),
    "render_working_context_summary": ("blink.brain.projections", "render_working_context_summary"),
    "resolve_brain_session_ids": ("blink.brain.session", "resolve_brain_session_ids"),
}


def __getattr__(name: str):
    """Resolve brain exports lazily to avoid provider-bound import side effects."""
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module 'blink.brain' has no attribute {name!r}")
    module_name, attr_name = target
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Expose the lazy export list to interactive tooling."""
    return sorted(set(globals()) | set(__all__))
